![logo_chico_1.jpg]()

![image.png]()


**pandas** es una herramienta de manipulación y análisis de datos de código abierto construida sobre el lenguaje de programación **Python** .

Algunas de las principales características de esta librería son:

* Define nuevas estructuras de datos basadas en los arrays de la librería NumPy pero con nuevas funcionalidades.
* Permite leer y escribir fácilmente archivos en formato CSV, Excel y bases de datos SQL.
* Permite acceder a los datos mediante índices o nombres para filas y columnas.
* Ofrece métodos para reordenar, dividir y combinar conjuntos de datos.



Link de Interés:

https://pandas.pydata.org/

https://pandas.pydata.org/docs/

In [ ]:
import pandas as pd

### ¿Qué estructuras de datos maneja pandas?

Pandas dispone de tres estructuras de datos diferentes:

* **Series:** Estructura de una dimensión.
* **DataFrame:** Estructura de dos dimensiones (tablas).
* **Panel:** Estructura de tres dimensiones (cubos).

#### Series

La **serie** es una matriz unidimensional etiquetada capaz de contener cualquier tipo de datos (enteros, cadenas, números de punto flotante, objetos Python, etc.). Son homogéneas, es decir, sus elementos tienen que ser del mismo tipo, y su tamaño es inmutable (no se puede cambiar) aunque si su contenido.

Son estructuras similares a los arrays de una dimensión.

In [ ]:
#Serie creada con una lista
una_serie = pd.Series(['Juan', 'María', 'Pedro', 'José', 'Catalina','Paula'], dtype='string')
print(una_serie)

0        Juan
1       María
2       Pedro
3        José
4    Catalina
5       Paula
dtype: string

In [ ]:
#Serie creada con un diccionario
otra_serie = pd.Series({'Juan': 8.5,  'Catalina': 7, 'Pedro': 10 , 'Mariela': 6})
print(otra_serie)

Juan         8.5
Catalina     7.0
Pedro       10.0
Mariela      6.0
dtype: float64

Métodos para ver las características de una serie:

* size :  Devuelve el número de elementos de la serie.
* index : Devuelve una lista con los nombres de las filas.
* dtype : Devuelve el tipo de datos de los elementos de la serie s.

In [ ]:
print(f'size {una_serie.size}')
print(f'index {una_serie.index}')
print(f'dtype {una_serie.dtype}')

size 6
index RangeIndex(start=0, stop=6, step=1)
dtype string

In [ ]:
print(f'size {otra_serie.size}')
print(f'index {otra_serie.index}')
print(f'dtype {otra_serie.dtype}')

size 4
index Index(['Juan', 'Catalina', 'Pedro', 'Mariela'], dtype='object')
dtype float64

Para acceder a los elementos de una serie se puede realizar por índice o por posición:

* serie[i] : Devuelve el elemento que ocupa la posición i+1 en la serie s.
* serie[posiciones]: Devuelve otra serie con los elementos que ocupan las posiciones de la lista posiciones.
* serie[nombre] : Devuelve el elemento con el nombre nombre en el índice.
* serie[nombres] : Devuelve otra serie con los elementos correspondientes a los nombres indicadas en la lista nombres en el índice.

In [ ]:
print(una_serie[0])

Juan

In [ ]:
print(una_serie[0:5])
print(una_serie[[1,2]])

0        Juan
1       María
2       Pedro
3        José
4    Catalina
dtype: string
1    María
2    Pedro
dtype: string

In [ ]:
print(otra_serie['Juan'])

8.5

In [ ]:
print(otra_serie[['Juan','Catalina']])

Juan        8.5
Catalina    7.0
dtype: float64

#### DataFrame

Un **DataFrame** es una estructura de datos bidimensional donde cada columna es un objeto de tipo Series. Todos los datos de una misma columna son del mismo tipo, y las filas son registros que pueden contener datos de distintos tipos.

Un DataFrame contiene dos índices, uno para las filas y otro para las columnas, y se puede acceder a sus elementos mediante los nombres de las filas y las columnas.

Se puede pensar como una una tabla SQL. Generalmente es el objeto pandas más utilizado.

In [ ]:
#DataFrame a partir de una lista
df1 = pd.DataFrame([['Juan','Pérez',25,'Ingeniero'], ['Luis','Gómez',30,'Abogado'], ['Antonio','Sánchez',20,'Médico']], columns=['nombre', 'apellido','edad','profesion'])
print(df1)

    nombre apellido  edad  profesion
0     Juan    Pérez    25  Ingeniero
1     Luis    Gómez    30    Abogado
2  Antonio  Sánchez    20     Médico

In [ ]:
#DataFrame a partir de un diccionario
datos = {'nombre':['Juan', 'Luis', 'Antonio'],
         'apellido':['Pérez','Gómez','Sánchez'],
         'edad':[25, 30, 35],
         'profesion':['Ingeniero', 'Abogado', 'Médico']
         }

df2 = pd.DataFrame(datos)
print(df2)

    nombre apellido  edad  profesion
0     Juan    Pérez    25  Ingeniero
1     Luis    Gómez    30    Abogado
2  Antonio  Sánchez    35     Médico

Métodos para ver las características de un DataFrame:

* info : Devuelve información (número de filas, número de columnas, índices, tipo de las columnas y memoria usado) sobre el DataFrame.
* shape : Devuelve una tupla con el número de filas y columnas del DataFrame.
* size : Devuelve el número de elementos del DataFrame.
* columns : Devuelve una lista con los nombres de las columnas del DataFrame.
* index : Devuelve una lista con los nombres de las filas del DataFrame df.
* dtypes : Devuelve una serie con los tipos de datos de las columnas del DataFrame.
* head(n) : Devuelve las n primeras filas del DataFrame.
* tail(n) : Devuelve las n últimas filas del DataFrame.

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   nombre     3 non-null      object
 1   apellido   3 non-null      object
 2   edad       3 non-null      int64
 3   profesion  3 non-null      object
dtypes: int64(1), object(3)
memory usage: 224.0+ bytes

In [ ]:
df1.dtypes

nombre       object
apellido     object
edad          int64
profesion    object
dtype: object

In [ ]:
df1.head(1)

  nombre apellido  edad  profesion
0   Juan    Pérez    25  Ingeniero

In [ ]:
df1.tail(2)

    nombre apellido  edad profesion
1     Luis    Gómez    30   Abogado
2  Antonio  Sánchez    20    Médico

El acceso a los datos de un DataFrame se puede hacer a través de posiciones o través de los nombres de las filas y columnas.

*Accesos mediante posiciones*

* df.iloc[i, j] : Devuelve el elemento que se encuentra en la fila i y la columna j del DataFrame df. Pueden indicarse secuencias de índices para obtener partes del DataFrame.
* df.iloc[filas, columnas] : Devuelve un DataFrame con los elementos de las filas de la lista filas y de las columnas de la lista columnas.
* df.iloc[i] : Devuelve una serie con los elementos de la fila i del DataFrame df.

*Acceso a los elementos mediante nombres*

* df.loc[fila, columna] : Devuelve el elemento que se encuentra en la fila con nombre fila y la columna de con nombre columna del DataFrame df.
* df.loc[filas, columnas] : Devuelve un DataFrame con los elemento que se encuentra en las filas con los nombres de la lista filas y las columnas con los nombres de la lista columnas del DataFrame df.
* df[columna] : Devuelve una serie con los elementos de la columna de nombre columna del DataFrame df.
* df.columna : Devuelve una serie con los elementos de la columna de nombre columna del DataFrame df. Es similar al método anterior pero sólo funciona cuando el nombre de la columna no tiene espacios en blanco.

In [ ]:
df1['apellido']

0      Pérez
1      Gómez
2    Sánchez
Name: apellido, dtype: object

In [ ]:
df1.apellido

0      Pérez
1      Gómez
2    Sánchez
Name: apellido, dtype: object

In [ ]:
df1.loc[1,'apellido']

'Gómez'

In [ ]:
df1.iloc[0]

nombre            Juan
apellido         Pérez
edad                25
profesion    Ingeniero
Name: 0, dtype: object

In [ ]:
df1.iloc[0,0]

'Juan'

##### Creación de DataFrame desde un archivo de datos

![image.png]()

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df3=pd.read_csv('/content/drive/MyDrive/Labo Datos/Notebooks Ciencia de Datos/datasets/ds_titanic.csv')
df3.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df3.to_csv('/content/drive/MyDrive/Labo Datos/Notebooks Ciencia de Datos/datasets/archivo_output.csv',index=False)

### Filtrar información

Crear máscaras para obtener las filas que cumplen con el patrón buscado

In [ ]:
df3["Sex"]=="male"

0       True
1      False
2      False
3      False
4       True
       ...
886     True
887    False
888    False
889     True
890     True
Name: Sex, Length: 891, dtype: bool

OR

In [ ]:
(df3["Sex"]=="male") | (df3["Pclass"] ==1)

0       True
1       True
2      False
3       True
4       True
       ...
886     True
887     True
888    False
889     True
890     True
Length: 891, dtype: bool

AND

In [ ]:
(df3["Sex"]=="male") & (df3["Pclass"] ==1)

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889     True
890    False
Length: 891, dtype: bool

Utilizamos las máscaras para selccionar filas

In [ ]:
df3[(df3["Sex"]=="male") | (df3["Pclass"] ==1)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,SibSp_Parch
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S,0
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,0
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,0

In [ ]:
filtro=(df3["Sex"]=="male") | (df3["Pclass"] ==1)
df3[filtro]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,SibSp_Parch
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S,0
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,0
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,0

### Creación de nuevas columnas

Creación de columna en función de la suma de los datos en otras 2

In [ ]:
df3["SibSp_Parch"]=df3["SibSp"]+df3["Parch"]
df3.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,SibSp_Parch
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0

Eliminar columna

In [ ]:
df3.drop("SibSp_Parch",axis=1,inplace=True)
df3.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
columnas_eliminar=["PassengerId","Name"]
df3.drop(columnas_eliminar,axis=1,inplace=True)
df3.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,1,female,35.0,1,0,113803,53.1000,C123,S
4,0,3,male,35.0,0,0,373450,8.0500,NaN,S

Eliminar filas

In [ ]:
mascara=df3["Sex"]=="male"
df3.drop(df3[mascara].index)

,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,1,female,35.0,1,0,113803,53.1000,C123,S
8,1,3,female,27.0,0,2,347742,11.1333,NaN,S
9,1,2,female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...
880,1,2,female,25.0,0,1,230433,26.0000,NaN,S
882,0,3,female,22.0,0,0,7552,10.5167,NaN,S
885,0,3,female,39.0,0,5,382652,29.1250,NaN,Q
887,1,1,female,19.0,0,0,112053,30.0000,B42,S
888,0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S

Renombrar columna

In [ ]:
columnas={"Pclass":"PassengerClass"}
df3.rename(columns = columnas, inplace = True)
df3.head(2)

,Survived,PassengerClass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C

### Tabla de doble entrada

In [ ]:
pd.crosstab(df3['Survived'],df3['Sex'])

Sex       female  male
Survived
0             81   468
1            233   109

### Agrupar

In [ ]:
df3.groupby(['PassengerClass','Sex'])['Survived'].sum()

PassengerClass  Sex
1               female    91
                male      45
2               female    70
                male      17
3               female    72
                male      47
Name: Survived, dtype: int64

### Reemplazar valores de columnas

In [ ]:
ds_trabajo_reemplazo_valores=df3.copy()

ds_trabajo_reemplazo_valores.loc[ds_trabajo_reemplazo_valores.loc[:,"Survived"]==1,"Survived"]=True
ds_trabajo_reemplazo_valores.loc[ds_trabajo_reemplazo_valores.loc[:,"Survived"]==0,"Survived"]=False

ds_trabajo_reemplazo_valores.head()

,Survived,PassengerClass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,True,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,True,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,True,1,female,35.0,1,0,113803,53.1000,C123,S
4,False,3,male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
ds_trabajo_reemplazo_valores=df3.copy()

ds_trabajo_reemplazo_valores.loc[:,"Survived"].replace(to_replace=[0,1],value=[False,True],inplace=True)

ds_trabajo_reemplazo_valores.head()

,Survived,PassengerClass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,True,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,True,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,True,1,female,35.0,1,0,113803,53.1000,C123,S
4,False,3,male,35.0,0,0,373450,8.0500,NaN,S

#<center> Merge</center>

Ejemplo extraido de https://github.com/shanealynn/Pandas-Merge

In [ ]:
user_usage = pd.read_csv("/content/drive/MyDrive/Labo Datos/Notebooks Ciencia de Datos/datasets/user_usage.csv")
user_device = pd.read_csv("/content/drive/MyDrive/Labo Datos/Notebooks Ciencia de Datos/datasets/user_device.csv")
devices = pd.read_csv("/content/drive/MyDrive/Labo Datos/Notebooks Ciencia de Datos/datasets/android_devices.csv")

devices.rename(columns={"Retail Branding": "manufacturer"}, inplace=True)

#### Merge 1

Supongamos que necesitamos obtener estadísticas de distintos tipos de dispositivos celulares.

Unamos los dataset user_usage con user_device utilizando la columna user_id, que se común a los dos.

In [ ]:
result = pd.merge(user_usage,
                 user_device[['use_id', 'platform', 'device']],
                 on='use_id')
result.head()

,outgoing_mins_per_month,outgoing_sms_per_month,monthly_mb,use_id,platform,device
0,21.97,4.82,1557.33,22787,android,GT-I9505
1,1710.08,136.88,7267.55,22788,android,SM-G930F
2,1710.08,136.88,7267.55,22789,android,SM-G930F
3,94.46,35.17,519.12,22790,android,D2303
4,71.59,79.26,1557.33,22792,android,SM-G361F

Veamos que pasó?

In [ ]:
print("Dimensiones user_usage: {}".format(user_usage.shape))
print("Dimensiones user_device : {}".format(user_device[['use_id', 'platform', 'device']].shape))
print("result",result.shape)
user_usage['use_id'].isin(user_device['use_id']).value_counts()

Dimensiones user_usage: (240, 4)
Dimensiones user_device : (272, 3)
result (159, 6)

True     159
False     81
Name: use_id, dtype: int64

Sólo obtenemos los registros con user_id en ambos datasets (159)

#### Merge 2 - Left join

Left join, mantiene todas las filas del dataset de la izquierda, en este caso "user_usage" mientras que las columnas del dataset de la derecha se completarán sólo si existen datos vinculados en esa tabla, sino se completan con valores Nan.

In [ ]:
result = pd.merge(user_usage,
                 user_device[['use_id', 'platform', 'device']],
                 on='use_id', how='left')

print("user_usage dimensions: {}".format(user_usage.shape))
print("result dimensions: {}".format(result.shape))
print("There are {} missing values in the result.".format(result['device'].isnull().sum()))

user_usage dimensions: (240, 4)
result dimensions: (240, 6)
There are 81 missing values in the result.

In [ ]:
result.head()

,outgoing_mins_per_month,outgoing_sms_per_month,monthly_mb,use_id,platform,device
0,21.97,4.82,1557.33,22787,android,GT-I9505
1,1710.08,136.88,7267.55,22788,android,SM-G930F
2,1710.08,136.88,7267.55,22789,android,SM-G930F
3,94.46,35.17,519.12,22790,android,D2303
4,71.59,79.26,1557.33,22792,android,SM-G361F

In [ ]:
result.tail()

,outgoing_mins_per_month,outgoing_sms_per_month,monthly_mb,use_id,platform,device
235,260.66,68.44,896.96,25008,NaN,NaN
236,97.12,36.50,2815.00,25040,NaN,NaN
237,355.93,12.37,6828.09,25046,NaN,NaN
238,632.06,120.46,1453.16,25058,NaN,NaN
239,488.70,906.92,3089.85,25220,NaN,NaN

#### Merge 3 - Right join

Right join, mantiene todas las filas del dataset de la derecha, en este caso "user_device" mientras que las columnas del dataset de la izquierda se completarán sólo si existen datos vinculados en esa tabla, sino se completan con valores Nan.

In [ ]:
result = pd.merge(user_usage,
                 user_device[['use_id', 'platform', 'device']],
                 on='use_id', how='right')

print("user_device dimensions: {}".format(user_device.shape))
print("result dimensions: {}".format(result.shape))
print("There are {} missing values in the 'monthly_mb' column in the result.".format(
        result['monthly_mb'].isnull().sum()))
print("There are {} missing values in the 'platform' column in the result.".format(
        result['platform'].isnull().sum()))

user_device dimensions: (272, 6)
result dimensions: (272, 6)
There are 113 missing values in the 'monthly_mb' column in the result.
There are 0 missing values in the 'platform' column in the result.

#### Merge 4 - Outer Join

Outer join mantiene todas las filas de ambos datasets, completando por cada fila los campos correspondientes a ambos datasets si se pueden vincular, y completando con Nans los campos correspondients al dataset derecho o izquierdo según corresponda en cada de no existir contraparte.

In [ ]:
print("There are {} unique values of use_id in our dataframes.".format(
        pd.concat([user_usage['use_id'], user_device['use_id']]).unique().shape[0]))
result = pd.merge(user_usage,
                 user_device[['use_id', 'platform', 'device']],
                 on='use_id', how='outer', indicator=True)

print("Outer merge result has {} rows.".format(result.shape))

print("There are {} rows with no missing values.".format(
    (result.apply(lambda x: x.isnull().sum(), axis=1) == 0).sum()))

There are 353 unique values of use_id in our dataframes.
Outer merge result has (353, 7) rows.
There are 159 rows with no missing values.

### Merge Final - sumemos un merge con la tabla user_device

In [ ]:
# First, add the platform and device to the user usage.
result = pd.merge(user_usage,
                 user_device[['use_id', 'platform', 'device']],
                 on='use_id',
                 how='left')

# Now, based on the "device" column in result, match the "Model" column in devices.
devices.rename(columns={"Retail Branding": "manufacturer"}, inplace=True)
result = pd.merge(result,
                  devices[['manufacturer', 'Model']],
                  left_on='device',
                  right_on='Model',
                  how='left')

result.head()

,outgoing_mins_per_month,outgoing_sms_per_month,monthly_mb,use_id,platform,device,manufacturer,Model
0,21.97,4.82,1557.33,22787,android,GT-I9505,Samsung,GT-I9505
1,1710.08,136.88,7267.55,22788,android,SM-G930F,Samsung,SM-G930F
2,1710.08,136.88,7267.55,22789,android,SM-G930F,Samsung,SM-G930F
3,94.46,35.17,519.12,22790,android,D2303,Sony,D2303
4,71.59,79.26,1557.33,22792,android,SM-G361F,Samsung,SM-G361F

Como resultado final calculamos algunas estadísticas por Marca de dispositivo

In [ ]:
result.groupby("manufacturer").agg({
        "outgoing_mins_per_month": "mean",
        "outgoing_sms_per_month": "mean",
        "monthly_mb": "mean",
        "use_id": "count"
    })

,outgoing_mins_per_month,outgoing_sms_per_month,monthly_mb,use_id
manufacturer,,,,
HTC,299.842955,93.059318,5144.077955,44
Huawei,81.526667,9.500000,1561.226667,3
LGE,111.530000,12.760000,1557.330000,2
Lava,60.650000,261.900000,12458.670000,2
Lenovo,215.920000,12.930000,1557.330000,2
Motorola,95.127500,65.666250,3946.500000,16
OnePlus,354.855000,48.330000,6575.410000,6
Samsung,191.010093,92.390463,4017.318889,108
Sony,177.315625,40.176250,3212.000625,16
Vodafone,42.750000,46.830000,5191.120000,1
ZTE,42.750000,46.830000,5191.120000,1